### PR TITLE
Feat/refactor seed db

### PR DESCRIPTION
**Pull request by EvaFro**
@davidseid can you look at this when you get a chance? I refactored how I was saving my database. I had to pull in a new library and move some files around. So hopefully it makes since. If it doesn't let me know. Thanks!

### CODE REVIEW

**Comment by davidseid** [comment]
Erin, great work here! I like your use of the mongoose-seed library and everything looks clean. One thing to maybe look into is that when I ran the seedDB script the database connection still didn't seem to close on its own despite the use of seeder.disconnect(). Was it closing for you? 

Otherwise everything looks great!

**Comment by EvaFro** [comment]
@davidseid did you pull this specific branch down? Because I haven't merged it yet. For me it did close. There was a conflict I had to resolve so maybe that is why? I will merge it right now and see if I get the same problem.

**Comment by davidseid** [comment]
Oops, yeah definitely was checking your most recent master not this specific branch! So I assume this is working then. All looks good.

**Comment by EvaFro** [comment]
no problem! I just merged it and it works just fine. I had to do an npm install agian for it to work, but it should work just fine.

**Pull request merged**
